x-xivrp: &defaults
  image: xivrp:dev
  tty: true

  build:
    context: .
    dockerfile: Dockerfile.dev
    args:
      UID: "${_UID}"

  volumes:
    - './:/opt/xivrp'
    - 'node_modules:/opt/xivrp/node_modules'

  env_file: '.env'
  environment:
    RAILS_DATABASE_HOST: 'xivrp-db'
    RAILS_DATABASE_USER: 'xivrp'
    RAILS_DATABASE_PASS: 'password'

services:
  xivrp:
    <<: *defaults
    command: ["bin/rails", "server", "--binding=0.0.0.0", "--port=3000", "--pid=/tmp/server.pid"]

    ports:
      - '3000:3000'

    depends_on:
      - 'xivrp-db'
      - 'xivrp-webpack'

  xivrp-webpack:
    <<: *defaults

    command: ["bin/webpack-dev-server"]

    ports:
      - '3035:3035'

  xivrp-db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: xivrp
      POSTGRES_PASSWORD: password
    volumes:
      - 'dbdata:/var/lib/postgresql/data'

volumes:
  node_modules:
  dbdata:
