FROM ruby:2.7-slim

RUN apt-get update && \
    apt-get install -y build-essential libpq-dev libxslt1-dev nodejs npm

ARG UID
ARG USERNAME=xivrp

RUN adduser --home /opt/xivrp --uid $UID $USERNAME

WORKDIR /opt/xivrp

COPY Gemfile Gemfile.lock ./

RUN gem install bundler -v "$(awk 'END { print $1 }' Gemfile.lock)" &&\
    bundle install

COPY package.json yarn.lock ./

RUN npm install -g yarn && yarn install

VOLUME /opt/xivrp

EXPOSE 3000

CMD [ "bin/rails", "c" ]